In [43]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

In [44]:
nhl_df=pd.read_csv("nhl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

In [52]:
nhl_df['team']=nhl_df['team'].str.replace('[\w.]*\ ', '')
nhl_df['team']=nhl_df['team'].str.replace('\*','')
cities['NHL']=cities['NHL'].str.replace('[\w.]*\ ', '')
cities['NHL']=cities['NHL'].str.replace('\*','')
nhlMask = nhl_df['team'] != 'Division'
nhl_df=nhl_df.where(nhlMask).dropna()
nhl_df['W']=pd.to_numeric(nhl_df['W'])
nhl_df['L']=pd.to_numeric(nhl_df['L'])

In [53]:
is_2018 = nhl_df['year']==2018
is_2018.head()

1    True
2    True
3    True
4    True
5    True
Name: year, dtype: bool

In [54]:
nhl_df_2018 = nhl_df[is_2018]
nhl_df_2018.shape

(31, 15)

In [55]:
nhl_df_2018.head()

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
1,Lightning,82,54,23,5,113,0.689,296,236,0.66,-0.07,0.634,48,2018.0,NHL
2,Bruins,82,50,20,12,112,0.683,270,214,0.62,-0.07,0.61,47,2018.0,NHL
3,Leafs,82,49,26,7,105,0.64,277,232,0.49,-0.06,0.567,42,2018.0,NHL
4,Panthers,82,44,30,8,96,0.585,248,246,-0.01,-0.04,0.537,41,2018.0,NHL
5,Wings,82,30,39,13,73,0.445,217,255,-0.48,-0.01,0.341,25,2018.0,NHL

In [56]:
display(cities.head())

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils[3]
1,Los Angeles,13310447,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[7]
3,Chicago,9512999,Bears[note 8],CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars

In [59]:
nhl_df_2018['W/L Ratio'] = nhl_df_2018['W'] / nhl_df_2018['L']
nhl_df_2018.head()

C:\Users\airfo\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League,W/L Ratio
1,Lightning,82,54,23,5,113,0.689,296,236,0.66,-0.07,0.634,48,2018.0,NHL,2.347826
2,Bruins,82,50,20,12,112,0.683,270,214,0.62,-0.07,0.61,47,2018.0,NHL,2.500000
3,Leafs,82,49,26,7,105,0.64,277,232,0.49,-0.06,0.567,42,2018.0,NHL,1.884615
4,Panthers,82,44,30,8,96,0.585,248,246,-0.01,-0.04,0.537,41,2018.0,NHL,1.466667
5,Wings,82,30,39,13,73,0.445,217,255,-0.48,-0.01,0.341,25,2018.0,NHL,0.769231

In [60]:
merged_nhl_df_2018 = pd.merge(nhl_df_2018, cities, how = 'inner', on = 'Metropolitan area')
merged2_nhl_df_2018 = merged_nhl_df_2018.set_index('Metropolitan area')

merged2_nhl_df_2018

KeyError: 'Metropolitan area'